//Vue.js のDefaultと同じ
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header_footer from "@/components/header-footer/header-footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      {/* Vue.jsでは<nuxt/>と同じ */}
      <body className={inter.className}>
        <div>
          <Header_footer />
          {children}
        </div>
      </body>
    </html>
  );
}
